apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: v1
data:
  pg_hba.conf: |
    local   all             all                                     trust
    # IPv4 local connections:
    host    all             all             0.0.0.0/0               trust
    # IPv6 local connections:
    host    all             all             ::1/128                 trust
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     trust
    host    replication     all             0.0.0.0/0               trust
    host    replication     all             ::1/128                 trust
kind: ConfigMap
metadata:
  name: pghbaconf
  namespace: sales-system
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: sales-system
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app: database
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: sales-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: sales-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  serviceName: database-service
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - args:
        - -c
        - hba_file=/etc/pg_hba.conf
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        image: 132172135366.dkr.ecr.us-east-1.amazonaws.com/ardanlabs/database:postgres-16.2
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 3500m
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
        - mountPath: /etc/pg_hba.conf
          name: config
          readOnly: false
          subPath: pg_hba.conf
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: database-data
      - configMap:
          items:
          - key: pg_hba.conf
            path: pg_hba.conf
          name: pghbaconf
        name: config
