apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: client

  template:
    metadata:
      labels:
        app: client
    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: client
        image: client-image

        ports:
        - name: client
          containerPort: 8080

        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /world
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /world
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu

        - name: GOGC
          value: "off"

        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

---

apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: sales-system

spec:
  selector:
    app: client
