apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales
    spec:
      terminationGracePeriodSeconds: 60

      initContainers:
      - name: init-migrate-seed
        image: sales-image
        command: ['./admin']

      containers:
      - name: sales
        image: sales-image
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system

spec:
  selector:
    app: sales
