apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales
    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: sales
        image: sales-image

        ports:
        - name: sales
          containerPort: 3000
        - name: sales-debug
          containerPort: 3010

        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /liveliness
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        resources:
          requests:
            cpu: "250m"     # I need access to 25ms/100ms on one core
            memory: "36Mi"  # Use this same value for limits
          limits:
            cpu: "250m"     # Execute instructions 25ms/100ms on one core
            memory: "36Mi"  # Match the requests value

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu

---

apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system

spec:
  selector:
    app: sales
