apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: sales-system
spec:
  ports:
  - name: client
    port: 8080
    targetPort: client
  selector:
    app: client
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: sales-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: GOGC
          value: "off"
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: 132172135366.dkr.ecr.us-east-1.amazonaws.com/ardanlabs/client:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /world
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: client
        ports:
        - containerPort: 8080
          name: client
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /world
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 36Mi
          requests:
            cpu: 250m
            memory: 36Mi
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
